test: 워크플로우 수정

diff --git a/.github/workflows/community_cicd.yml b/.github/workflows/community_cicd.yml
--- a/.github/workflows/community_cicd.yml
+++ b/.github/workflows/community_cicd.yml
@@ -29,40 +29,40 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
 
-    - name: Gradle Caching
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.gradle/caches
-          ~/.gradle/wrapper
-        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-        restore-keys: |
-          ${{ runner.os }}-gradle-
+    # - name: Gradle Caching
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: |
+    #       ~/.gradle/caches
+    #       ~/.gradle/wrapper
+    #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+    #     restore-keys: |
+    #       ${{ runner.os }}-gradle-
     
-    - name: Grant Execute Permission For Gradlew
-      run: chmod +x gradlew
-      working-directory: community
+    # - name: Grant Execute Permission For Gradlew
+    #   run: chmod +x gradlew
+    #   working-directory: community
 
-    - name: Build With Gradle
-      run: ./gradlew build -x test
-      working-directory: community
+    # - name: Build With Gradle
+    #   run: ./gradlew build -x test
+    #   working-directory: community
       
-    # build Test
-    - name: 테스트 코드 실행
-      run: ./gradlew --info test
-      working-directory: community
+    # # build Test
+    # - name: 테스트 코드 실행
+    #   run: ./gradlew --info test
+    #   working-directory: community
 
-    - name: Publish Unit Test Results
-      uses: EnricoMi/publish-unit-test-result-action@v1
-      if: ${{ always() }}
-      with:
-        files: build/test-results/**/*.xml
+    # - name: Publish Unit Test Results
+    #   uses: EnricoMi/publish-unit-test-result-action@v1
+    #   if: ${{ always() }}
+    #   with:
+    #     files: build/test-results/**/*.xml
         
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/build/test-results/test/TEST-*.xml'
+    # - name: Publish Test Report
+    #   uses: mikepenz/action-junit-report@v3
+    #   if: success() || failure() # always run even if the previous step fails
+    #   with:
+    #     report_paths: '**/build/test-results/test/TEST-*.xml'
 
     # CD
     - name: Docker build & Push
@@ -83,6 +83,7 @@ jobs:
         envs: APP, COMPOSE
         #script_stop: true
         script: |
+          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
           sudo docker-compose -f $COMPOSE down
           sudo docker pull ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_REPO }}
           sudo docker-compose -f $COMPOSE up -d
